name: Build Kernel LTO

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Kernel branch
        default: 'main'
        required: true
      SELINUX_PERMISSIVE:
        description: Permissive SELinux
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: rasolarmand114-tech/exlinux-
          path: kernel_root
          ref: ${{ github.event.inputs.BRANCH }}
          fetch-depth: 0

      - name: Prepare dependencies + fetch tags
        working-directory: kernel_root
        run: |
          sudo apt update -y
          sudo apt install -y \
            bc cpio flex bison git python-is-python3 \
            tar perl wget curl lz4 libssl-dev
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --tags --force
      - name: Recreate 12GB Swap
        run: |
          sudo swapoff -a || true
          sudo rm -f /swapfile
          sudo fallocate -l 12G /swapfile || sudo dd if=/dev/zero of=/swapfile bs=1M count=12288
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h
      - name: Fetch toolchains (Proton Clang + GCC 4.9)
        run: |
          mkdir toolchains && cd toolchains
          git clone --depth=1 https://github.com/rasolarmand114-tech/proton-clang.git clang
          git clone --depth=1 -b androidcc-4.9 https://github.com/rsuntk/toolchains.git google
        working-directory: kernel_root

      - name: Set timezone (Asia/Kolkata)
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
      - name: Build kernel
        id: buildKernel
        run: |
          export PATH=$(pwd)/toolchains/clang/bin:$PATH
          export CROSS_COMPILE=$(pwd)/toolchains/google/bin/aarch64-linux-android-
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export LLVM_IAS=0
          export CC=clang
          export LD=${CROSS_COMPILE}ld
          export AS=${CROSS_COMPILE}as
          export AR=${CROSS_COMPILE}ar
          export NM=${CROSS_COMPILE}nm
          export OBJCOPY=${CROSS_COMPILE}objcopy
          export OBJDUMP=${CROSS_COMPILE}objdump
          export STRIP=${CROSS_COMPILE}strip
          export KBUILD_BUILD_USER="exlinux"
          export KBUILD_BUILD_HOST="github"
          export BUILD_START=`date`
          export IS_CI=true
          
          export DEFCONFIG="exlinux_defconfig"
          export DEVICE_ID="A12s"
          export KERNEL_SOURCE="https://github.com/rasolarmand114-tech/exlinux-"
          if [[ "${{ github.event.inputs.SELINUX_PERMISSIVE }}" == 'true' ]]; then
          echo "Switching SELinux to Permissive mode..."
          
          # Set permissive mode in defconfig
          echo "CONFIG_SECURITY_SELINUX_ALWAYS_PERMISSIVE=y" >> arch/arm64/configs/$DEFCONFIG
          grep "PERMISSIVE" arch/arm64/configs/$DEFCONFIG
    
          SELINUX_STATE="Permissive"
          else
          SELINUX_STATE="Enforcing"
          fi

          # Show final SELinux state
          echo "SELinux is set to: $SELINUX_STATE"

          bash $(pwd)/build_kernel.sh kernel --jobs $(nproc --all) $DEFCONFIG

        

  
          mv .config build_config.txt
          gitsha1=$(git rev-parse --short HEAD)
          buildDetails="`make kernelversion`-`echo $DEVICE`_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
        working-directory: kernel_root   

      - name: Upload kernel images
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-${{ steps.buildKernel.outputs.buildDetails }}
          path: |
            kernel_root/arch/arm64/boot/Image
            kernel_root/arch/arm64/boot/dts/exynos/*.dtb
            kernel_root/arch/arm64/boot/dts/samsung/*.dtb
